# Generated by Django 5.2.5 on 2025-10-05 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='control_por_lote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='control_por_serie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_estandar',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='ficha_tecnica_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto_iva',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='punto_reorden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='SKU_TEMP', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='uom_compra',
            field=models.CharField(default='unidad', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='uom_venta',
            field=models.CharField(default='unidad', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
        ),
        migrations.DeleteModel(
            name='Produccion',
        ),
        migrations.DeleteModel(
            name='SolicitudCompra',
        ),
    ]
