# Generated by Django 5.2.5 on 2025-11-04 20:36

import django.core.validators
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen de perfil (JPG, JPEG, PNG - máximo 2MB)', null=True, upload_to=usuarios.models.user_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
