# Generated by Django 5.2.5 on 2025-11-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('EDITOR', 'Editor'), ('LECTOR', 'Lector')], default='LECTOR', max_length=20),
        ),
    ]
