# Generated by Django 5.2.5 on 2025-11-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador del Sistema'), ('GERENTE_GENERAL', 'Gerente General'), ('GERENTE_INVENTARIO', 'Gerente de Inventario'), ('GERENTE_VENTAS', 'Gerente de Ventas'), ('SUPERVISOR_INVENTARIO', 'Supervisor de Inventario'), ('OPERADOR_INVENTARIO', 'Operador de Inventario'), ('VENDEDOR', 'Vendedor'), ('CONTADOR', 'Contador'), ('LECTOR', 'Solo Lectura')], default='LECTOR', max_length=30),
        ),
    ]
