# Generated by Django 5.2.5 on 2025-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_puede_crear_inventario_and_more'),
    ]

    operations = [
        # Remover campos que no están en el modelo actual
        migrations.RemoveField(
            model_name='usuario',
            name='puede_eliminar_productos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puede_eliminar_proveedores',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puede_eliminar_usuarios',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puede_exportar_datos',
        ),
        
        # Agregar campos faltantes
        migrations.AddField(
            model_name='usuario',
            name='puede_desactivar_productos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_desactivar_proveedores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_desactivar_usuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_exportar_usuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_exportar_productos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_exportar_proveedores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_exportar_inventario',
            field=models.BooleanField(default=False),
        ),
    ]