# Generated by Django 5.2.5 on 2025-11-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_add_missing_permission_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='puede_eliminar_inventario',
        ),
    ]
