# Generated by Django 5.2.5 on 2025-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha',
            field=models.DateField(),
        ),
    ]
